version: '3.7'
services:
  redis-master:
    image: redis:5
    ports:
      - "6379:6379"
  redis-slave:
    image: redis:5
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
  redis-sentinel:
    build:
      context: sentinel
    ports:
      - "26379:26379"
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    links:
      - redis-master
      - redis-slave
  memcached:
   image: memcached
   ports:
     - "11211:11211"